# {json:scada} Docker Compilation for Linux x64 - (c) 2020-2024 - Ricardo L. Olsen 
# Requires Internet connection!

services:

  dotnet_compile:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: js_dotnet_compile
    command: sh -c "cd /src/lib60870.netcore/lib60870.netcore/ && 
                    dotnet build --self-contained --runtime linux-x64 -c Release -o /publish_bin/ &&
                    cd /src/lib60870.netcore/iec101client/ &&
                    dotnet publish --self-contained --runtime linux-x64 -p:PublishReadyToRun=true -c Release -o /publish_bin/ &&
                    rm -rf obj bin &&
                    cd /src/lib60870.netcore/iec101server/ &&
                    dotnet publish --self-contained --runtime linux-x64 -p:PublishReadyToRun=true -c Release -o /publish_bin/ &&
                    rm -rf obj bin &&
                    cd /src/lib60870.netcore/iec104client/ &&
                    dotnet publish --self-contained --runtime linux-x64 -p:PublishReadyToRun=true -c Release -o /publish_bin/ &&
                    rm -rf obj bin &&
                    cd /src/lib60870.netcore/iec104server/ &&
                    dotnet publish --self-contained --runtime linux-x64 -p:PublishReadyToRun=true -c Release -o /publish_bin/ &&
                    rm -rf obj bin &&
                    cd /src/lib60870.netcore/lib60870.netcore/ &&
                    rm -rf obj bin &&
                    cd /src/OPC-UA-Client/ && 
                    dotnet publish --self-contained --runtime linux-x64 -p:PublishReadyToRun=true -c Release -o /publish_bin/ &&
                    rm -rf obj bin &&
                    cd /src/libplctag/libplctag.NET/src/libplctag &&
                    dotnet build --self-contained --runtime linux-x64 -c Release -o /publish_bin/ &&
                    cd /src/libplctag/PLCTagsClient &&
                    dotnet publish --self-contained --runtime linux-x64 -p:PublishReadyToRun=true -c Release -o /publish_bin/ &&
                    rm -rf obj bin &&
                    cd /src/libplctag/libplctag.NET/src/libplctag &&
                    rm -rf obj bin &&
                    apt-get update &&
                    apt-get -y install gcc make &&
                    cd /src/libiec61850 &&
                    make WITH_MBEDTLS3=1 &&
                    make install &&
                    cd dotnet/core/2.0/IEC61850.NET.core.2.0 &&
                    dotnet publish --no-self-contained --runtime linux-x64 -c Release &&
                    cd /src/iec61850_client &&
                    dotnet publish --no-self-contained --runtime linux-x64 -p:PublishReadyToRun=true -c Release -o /publish_bin/ &&
                    rm -rf obj bin &&
                    cd /src/libiec61850/dotnet/core/2.0/IEC61850.NET.core.2.0/ &&
                    rm -rf obj bin &&
                    cd /src/libiec61850 &&
                    rm -rf .install "
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
    #command: tail -f /dev/null
    volumes:
      - ../src/iec61850_client:/src/iec61850_client
      - ../src/libiec61850:/src/libiec61850
      - ../src/lib60870.netcore:/src/lib60870.netcore
      - ../src/OPC-UA-Client:/src/OPC-UA-Client
      - ../src/libplctag:/src/libplctag
      - ../demo-docker/bin:/publish_bin

  # NOTICE Dnp3Client and OPC-DA-Client are Windows-only, so it can only run in docker/linux using Wine.
  dotnet_compile_win:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: js_dotnet_compile_win
    command: sh -c "cd /src/OPC-DA-Client/ &&
                    dotnet publish --self-contained --runtime win-x64 -p:PublishReadyToRun=false -f net6.0-windows -c Release -o /publish_bin_win/ OPC-DA-Client.csproj &&
                    rm -rf obj bin &&
                    cd /src/dnp3/Dnp3Client/ &&
                    dotnet publish --self-contained --runtime win-x64 -p:PublishReadyToRun=false -c Release -o /publish_bin_win/ Dnp3Client.csproj &&
                    rm -rf obj bin &&
                    cp Dependencies/OpenSSL/*.dll /publish_bin_win/ "
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
    #command: tail -f /dev/null
    volumes:
      - ../demo-docker/bin_win:/publish_bin_win
      - ../src/dnp3:/src/dnp3
      - ./Dnp3Client.csproj:/src/dnp3/Dnp3Client/Dnp3Client.csproj
      - ../src/OPC-DA-Client:/src/OPC-DA-Client
      - ./OPC-DA-Client.csproj:/src/OPC-DA-Client/OPC-DA-Client.csproj
      - ../src/opcdaaehda-client-solution-net:/src/opcdaaehda-client-solution-net

  calculations_compile:
    image: golang:alpine
    container_name: js_calculations_compile
    command: sh -c "apk update &&
                    apk add --no-cache git && 
                    go env -w GO111MODULE=auto &&
                    cd /go/src/calculations/ && 
                    go mod tidy && 
                    go build && 
                    cp calculations /publish_bin/"
    volumes:
      - ../src/calculations:/go/src/calculations
      - ../demo-docker/bin:/publish_bin

  i104m_compile:
    image: golang:alpine
    container_name: js_i104m_compile
    command: sh -c "apk update &&
                    apk add --no-cache git && 
                    go env -w GO111MODULE=auto &&
                    cd /go/src/i104m/ &&
                    go mod tidy && 
                    go build && 
                    cp i104m /publish_bin/"
    volumes:
      - ../src/i104m:/go/src/i104m
      - ../demo-docker/bin:/publish_bin

  plc4x_compile:
    image: golang:alpine
    container_name: js_pcl4x_compile
    command: sh -c "apk update &&
                    apk add --no-cache git libpcap-dev gcc musl-dev && 
                    go env -w GO111MODULE=auto CGO_ENABLED=1 &&
                    cd /go/src/plc4x-client/ &&
                    go mod tidy && 
                    CGO_ENABLED=1 go build && 
                    cp plc4x-client /publish_bin/"
    volumes:
      - ../src/plc4x-client:/go/src/plc4x-client
      - ../demo-docker/bin:/publish_bin

  cs_data_processor_update:
    image: node:20-alpine
    container_name: js_cs_data_processor_update
    command:  sh -c "apk add --update npm && npm install -g npm && cd /cs_data_processor && npm install && chmod -R 777 node_modules"
    volumes:
      - ../src/cs_data_processor:/cs_data_processor

  cs_custom_processor_update:
    image: node:20-alpine
    container_name: js_cs_custom_processor_update
    command:  sh -c "apk add --update npm && npm install -g npm && cd /cs_custom_processor && npm install && chmod -R 777 node_modules"
    volumes:
      - ../src/cs_custom_processor:/cs_custom_processor

  server_realtime_update:
    image: node:20-alpine
    container_name: js_server_realtime_update
    command:  sh -c "apk add --update npm && npm install -g npm && cd /server_realtime && npm install && chmod -R 777 node_modules"
    volumes:
      - ../src/server_realtime:/server_realtime

  config_server_excel_update:
    image: node:20-alpine
    container_name: js_config_server_update
    command:  sh -c "apk add --update npm && npm install -g npm && cd /config_server_for_excel && npm install && chmod -R 777 node_modules"
    volumes:
      - ../src/config_server_for_excel:/config_server_for_excel

  server_realtime_auth_update:
    image: node:20-alpine
    container_name: js_server_realtime_auth_update
    command:  sh -c "apk add --update npm && npm install -g npm && cd /server_realtime_auth && npm install && chmod -R 777 node_modules"
    volumes:
      - ../src/server_realtime_auth:/server_realtime_auth

  alarm_beep_update:
    image: node:20-alpine
    container_name: js_alarm_beep_update
    command:  sh -c "apk add --update npm && npm install -g npm && cd /alarm_beep && npm install && chmod -R 777 node_modules"
    volumes:
      - ../src/alarm_beep:/alarm_beep

  oshmi2json_update:
    image: node:20-alpine
    container_name: js_oshmi2json_update
    command:  sh -c "apk add --update npm && npm install -g npm && cd /oshmi2json && npm install && chmod -R 777 node_modules"
    volumes:
      - ../src/oshmi2json:/oshmi2json

  telegraf_listener_update:
    image: node:20-alpine
    container_name: js_telegraf_listener_update
    command:  sh -c "apk add --update npm && npm install -g npm && cd /telegraf-listener && npm install && chmod -R 777 node_modules"
    volumes:
      - ../src/telegraf-listener:/telegraf-listener

  opcua_server_update:
    image: node:20-alpine
    container_name: js_opcua_server_update
    command:  sh -c "apk add --update npm && npm install -g npm && cd /OPC-UA-Server && npm install && chmod -R 777 node_modules"
    volumes:
      - ../src/OPC-UA-Server:/OPC-UA-Server

  mqtt_sparkplug_update:
    image: node:20-alpine
    container_name: js_mqtt_sparkplug_update
    command:  sh -c "apk add --update npm && npm install -g npm && cd /mqtt-sparkplug && npm install"
    volumes:
      - ../src/mqtt-sparkplug:/mqtt-sparkplug

  htdocs_admin_update:
    image: node:20-alpine
    container_name: js_admin_ui_update
    command:  sh -c "apk add --update npm && npm install -g npm && cd /AdminUI && npm install && npm run build && chmod -R 777 node_modules"
    volumes:
      - ../src/AdminUI:/AdminUI
